import type { ServiceDirectoryEntry } from '../../../domain/services/types';
import { pendingReview } from './pendingReview';

export const canoasEmergencyAndCapsServices = [
  // --- CANOAS: UPAs e Pronto Atendimento ---
  {
    id: 'canoas-upa-rio-branco',
    name: 'UPA Rio Branco',
    type: 'UPA 24h',
    badgeTone: 'secondary',
    city: 'Canoas',
    state: 'RS',
    address: 'Rua Cairu, 600 – Rio Branco, Canoas/RS',
    phoneDisplay: '(51) 3415-4500',
    phoneHref: 'tel:5134154500',
    hours: '24 horas',
    lat: -29.9388,
    lng: -51.1897,
    review: pendingReview,
  },
  {
    id: 'canoas-upa-liberty-dick-conter',
    name: 'UPA Liberty Dick Conter',
    type: 'UPA 24h',
    badgeTone: 'secondary',
    city: 'Canoas',
    state: 'RS',
    address: 'Rua Caçapava, 201 – Mathias Velho, Canoas/RS',
    phoneDisplay: '(51) 3415-4566',
    phoneHref: 'tel:5134154566',
    hours: '24 horas',
    lat: -29.9079,
    lng: -51.1963,
    review: pendingReview,
  },
  {
    id: 'canoas-upa-guajuviras',
    name: 'UPA Guajuviras',
    type: 'UPA 24h',
    badgeTone: 'secondary',
    city: 'Canoas',
    state: 'RS',
    address: 'Av. Boqueirão, 2.901 – Estância Velha, Canoas/RS',
    phoneDisplay: '(51) 3476-3698',
    phoneHref: 'tel:5134763698',
    hours: '24 horas',
    lat: -29.9035,
    lng: -51.1448,
    review: pendingReview,
  },
  {
    id: 'canoas-upa-sudeste-niteroi',
    name: 'UPA Sudeste / Niterói',
    type: 'UPA 24h',
    badgeTone: 'secondary',
    city: 'Canoas',
    state: 'RS',
    address: 'Rua Primeiro de Maio, 534 – Niterói, Canoas/RS',
    phoneDisplay: '(51) 3476-3448',
    phoneHref: 'tel:5134763448',
    hours: '24 horas',
    lat: -29.9351,
    lng: -51.1738,
    review: pendingReview,
  },
  {
    id: 'canoas-upa-do-idoso',
    name: 'UPA do Idoso',
    type: 'Pronto Atendimento',
    badgeTone: 'secondary',
    city: 'Canoas',
    state: 'RS',
    address: 'Rua Brasil, 438 – Centro, Canoas/RS',
    phoneDisplay: '(51) 3236-1632',
    phoneHref: 'tel:5132361632',
    hours: 'Pronto atendimento',
    lat: -29.9198,
    lng: -51.1791,
    review: pendingReview,
  },

  // --- CANOAS: CAPS ---
  {
    id: 'canoas-caps-praca-brasil',
    name: 'CAPS II Praça Brasil',
    type: 'CAPS',
    badgeTone: 'primary',
    city: 'Canoas',
    state: 'RS',
    address: 'Av. Getúlio Vargas, 7071 - Centro, Canoas - RS',
    phoneDisplay: '(51) 3236-1500',
    phoneHref: 'tel:5132361500',
    hours: 'Segunda a Sexta, 08:00 - 18:00',
    lat: -29.9145,
    lng: -51.1812,
    review: pendingReview,
  },
  {
    id: 'canoas-caps-novos-tempos',
    name: 'CAPS II Novos Tempos',
    type: 'CAPS',
    badgeTone: 'primary',
    city: 'Canoas',
    state: 'RS',
    address: 'Rua São Caetano, 102 – Marechal Rondon, Canoas/RS',
    phoneDisplay: '(51) 3076-9741',
    phoneHref: 'tel:5130769741',
    hours: 'Segunda a Sexta, 08:00 - 18:00',
    lat: -29.9073,
    lng: -51.1712,
    review: pendingReview,
  },
  {
    id: 'canoas-caps-recanto-girassois',
    name: 'CAPS III Recanto dos Girassóis',
    type: 'CAPS',
    badgeTone: 'primary',
    city: 'Canoas',
    state: 'RS',
    address: 'Rua Domingos Martins, 310 – Centro, Canoas/RS',
    phoneDisplay: '(51) 3076-9744',
    phoneHref: 'tel:5130769744',
    hours: '24 horas',
    lat: -29.9176,
    lng: -51.1865,
    review: pendingReview,
  },
  {
    id: 'canoas-caps-ad-travessia',
    name: 'CAPS AD III Travessia',
    type: 'CAPS',
    badgeTone: 'primary',
    city: 'Canoas',
    state: 'RS',
    address: 'Av. Guilherme Schell, 6250 - Centro, Canoas - RS',
    phoneDisplay: '(51) 3476-8800',
    phoneHref: 'tel:5134768800',
    hours: '24 horas',
    lat: -29.9161,
    lng: -51.1824,
    review: pendingReview,
  },
] satisfies ServiceDirectoryEntry[];

export const canoasClinicServices = [
  // --- Clínicas-escola e UBS ---
  {
    id: 'canoas-ubs-centro',
    name: 'UBS Centro de Saúde',
    type: 'UBS',
    badgeTone: 'secondary',
    city: 'Canoas',
    state: 'RS',
    address: 'Rua Quinze de Janeiro, 123 - Centro, Canoas - RS',
    phoneDisplay: '(51) 3462-1600',
    phoneHref: 'tel:5134621600',
    hours: 'Segunda a Sexta, 07:30 - 17:00',
    lat: -29.9192,
    lng: -51.1795,
    review: pendingReview,
  },
  {
    id: 'canoas-ulbra-clinica-psicologia',
    name: 'Clínica Escola de Psicologia - Ulbra',
    type: 'UNIVERSIDADE',
    badgeTone: 'neutral',
    city: 'Canoas',
    state: 'RS',
    address: 'Av. Farroupilha, 8001 - São José, Canoas - RS',
    phoneDisplay: '(51) 3477-9200',
    phoneHref: 'tel:5134779200',
    notes: 'Mediante agendamento prévio com valor social',
    lat: -29.9011,
    lng: -51.1578,
    review: pendingReview,
  },
] satisfies ServiceDirectoryEntry[];

export const canoasServicesList = [
  ...canoasEmergencyAndCapsServices,
  ...canoasClinicServices,
] satisfies ServiceDirectoryEntry[];
