import type { ServiceDirectoryEntry } from '../../../domain/services/types';
import { pendingReview } from './pendingReview';

export const esteioSapucaiaServices = [
  // --- ESTEIO E SAPUCAIA DO SUL ---
  {
    id: 'esteio-hospital-sao-camilo',
    name: 'Hospital São Camilo – Esteio',
    type: 'Hospital / Pronto-socorro 24h',
    badgeTone: 'secondary',
    city: 'Esteio',
    state: 'RS',
    address: 'Rua Castro Alves, 948 – Tamandaré, Esteio/RS',
    phoneDisplay: '(51) 2126-8300',
    phoneHref: 'tel:5121268300',
    hours: '24 horas',
    lat: -29.8542,
    lng: -51.1819,
    review: pendingReview,
  },
  {
    id: 'esteio-caps-aquarela',
    name: 'CAPS II Aquarela',
    type: 'CAPS',
    badgeTone: 'primary',
    city: 'Esteio',
    state: 'RS',
    address: 'Rua dos Ferroviários, 335 – Centro, Esteio/RS',
    phoneDisplay: '(51) 3473-0376',
    phoneHref: 'tel:5134730376',
    hours: 'Segunda a Sexta, 08:00 - 18:00',
    lat: -29.8572,
    lng: -51.1823,
    review: pendingReview,
  },
  {
    id: 'esteio-caps-ad-maos-dadas',
    name: 'CAPS AD Mãos Dadas',
    type: 'CAPS',
    badgeTone: 'primary',
    city: 'Esteio',
    state: 'RS',
    address: 'Rua 24 de Agosto, 500 – Centro, Esteio/RS',
    phoneDisplay: '(51) 2700-4370',
    phoneHref: 'tel:5127004370',
    hours: 'Álcool e outras drogas',
    lat: -29.8519,
    lng: -51.1802,
    review: pendingReview,
  },
  {
    id: 'sapucaia-upa-24h',
    name: 'UPA 24h Sapucaia do Sul',
    type: 'UPA 24h',
    badgeTone: 'secondary',
    city: 'Sapucaia do Sul',
    state: 'RS',
    address: 'ERS-118, esquina com Rua Ursa Maior – Nova Sapucaia, Sapucaia do Sul/RS',
    phoneDisplay: '(51) 3450-3082',
    phoneHref: 'tel:5134503082',
    hours: '24 horas',
    lat: -29.8247,
    lng: -51.1264,
    review: pendingReview,
  },
  {
    id: 'sapucaia-hospital-getulio-vargas',
    name: 'Hospital Municipal Getúlio Vargas – Sapucaia do Sul',
    type: 'Hospital / Pronto-socorro 24h',
    badgeTone: 'secondary',
    city: 'Sapucaia do Sul',
    state: 'RS',
    address: 'Rua Pinheiro Machado, 331 – Dihel, Sapucaia do Sul/RS',
    phoneDisplay: '(51) 3451-8200',
    phoneHref: 'tel:5134518200',
    hours: '24 horas',
    lat: -29.8329,
    lng: -51.1458,
    review: pendingReview,
  },
  {
    id: 'sapucaia-caps-bem-estar',
    name: 'CAPS II Bem Estar',
    type: 'CAPS',
    badgeTone: 'primary',
    city: 'Sapucaia do Sul',
    state: 'RS',
    address: 'Rua General Osório, esq. Rua Guerreiro Lima, s/nº – Sapucaia do Sul/RS',
    phoneDisplay: '(51) 3474-1833',
    phoneHref: 'tel:5134741833',
    hours: 'Segunda a Sexta, 08:00 - 18:00',
    lat: -29.8291,
    lng: -51.1462,
    review: pendingReview,
  },
  {
    id: 'sapucaia-caps-ad',
    name: 'CAPS AD Sapucaia do Sul',
    type: 'CAPS',
    badgeTone: 'primary',
    city: 'Sapucaia do Sul',
    state: 'RS',
    address: 'Rua Alfredo Juliano, 560 – Primor, Sapucaia do Sul/RS',
    phoneDisplay: '(51) 3474-4470',
    phoneHref: 'tel:5134744470',
    hours: 'Álcool e outras drogas',
    lat: -29.8354,
    lng: -51.1387,
    review: pendingReview,
  },
] satisfies ServiceDirectoryEntry[];
