import type { ServiceDirectoryEntry } from '../../../domain/services/types';
import { pendingReview } from './pendingReview';

export const novoHamburgoServices = [
  // --- NOVO HAMBURGO: UPAs, Hospitais e CAPS ---
  {
    id: 'nh-upa-centro',
    name: 'UPA Centro – Novo Hamburgo',
    type: 'UPA 24h',
    badgeTone: 'secondary',
    city: 'Novo Hamburgo',
    state: 'RS',
    address: 'Rua Visconde de Taunay, 134 – Rio Branco, Novo Hamburgo/RS',
    phoneDisplay: '(51) 3600-3123',
    phoneHref: 'tel:5136003123',
    hours: '24 horas',
    lat: -29.6914,
    lng: -51.1347,
    review: pendingReview,
  },
  {
    id: 'nh-upa-canudos',
    name: 'UPA Canudos – Novo Hamburgo',
    type: 'UPA 24h',
    badgeTone: 'secondary',
    city: 'Novo Hamburgo',
    state: 'RS',
    address: 'Rua Bartolomeu de Gusmão, 12 – Canudos, Novo Hamburgo/RS',
    phoneDisplay: '(51) 3097-1417',
    phoneHref: 'tel:5130971417',
    hours: '24 horas',
    lat: -29.6789,
    lng: -51.1098,
    review: pendingReview,
  },
  {
    id: 'nh-hospital-municipal',
    name: 'Hospital Municipal de Novo Hamburgo',
    type: 'Hospital / Pronto-socorro 24h',
    badgeTone: 'secondary',
    city: 'Novo Hamburgo',
    state: 'RS',
    address: 'Av. Pedro Adams Filho, 6520 – Operário, Novo Hamburgo/RS',
    phoneDisplay: '(51) 3272-3272',
    phoneHref: 'tel:5132723272',
    hours: '24 horas',
    lat: -29.6978,
    lng: -51.1275,
    review: pendingReview,
  },
  {
    id: 'nh-caps-canudos',
    name: 'CAPS Canudos',
    type: 'CAPS',
    badgeTone: 'primary',
    city: 'Novo Hamburgo',
    state: 'RS',
    address: 'Av. General Daltro Filho, 1660 – Canudos, Novo Hamburgo/RS',
    phoneDisplay: '(51) 3582-4206',
    phoneHref: 'tel:5135824206',
    hours: 'Segunda a Sexta, 08:00 - 18:00',
    lat: -29.6791,
    lng: -51.1112,
    review: pendingReview,
  },
  {
    id: 'nh-caps-santo-afonso',
    name: 'CAPS Santo Afonso',
    type: 'CAPS',
    badgeTone: 'primary',
    city: 'Novo Hamburgo',
    state: 'RS',
    address: 'Rua Babaçu, 58 – Santo Afonso, Novo Hamburgo/RS',
    phoneDisplay: '(51) 3580-1297',
    phoneHref: 'tel:5135801297',
    hours: 'Segunda a Sexta, 08:00 - 18:00',
    lat: -29.7182,
    lng: -51.1294,
    review: pendingReview,
  },
  {
    id: 'nh-caps-centro',
    name: 'CAPS Centro Novo Hamburgo',
    type: 'CAPS',
    badgeTone: 'primary',
    city: 'Novo Hamburgo',
    state: 'RS',
    address: 'Rua Joaquim Pedro Soares, 198 – Centro, Novo Hamburgo/RS',
    phoneDisplay: '(51) 3593-9573',
    phoneHref: 'tel:5135939573',
    hours: 'Segunda a Sexta, 08:00 - 18:00',
    lat: -29.6874,
    lng: -51.1291,
    review: pendingReview,
  },
  {
    id: 'nh-caps-ad-3',
    name: 'CAPS AD III Novo Hamburgo',
    type: 'CAPS',
    badgeTone: 'primary',
    city: 'Novo Hamburgo',
    state: 'RS',
    address: 'Rua Visconde de Taunay, 164 – Rio Branco, Novo Hamburgo/RS',
    phoneDisplay: '(51) 3600-8362',
    phoneHref: 'tel:5136008362',
    hours: '24 horas (Álcool e outras drogas)',
    lat: -29.6918,
    lng: -51.1352,
    review: pendingReview,
  },
] satisfies ServiceDirectoryEntry[];
