import type { ServiceDirectoryEntry } from '../../../domain/services/types';
import { pendingReview } from './pendingReview';

export const portoAlegreServices = [
  // --- PORTO ALEGRE: UPAs, Pronto Atendimentos, Hospitais e CAPS ---
  {
    id: 'poa-upa-moacyr-scliar',
    name: 'UPA Zona Norte Moacyr Scliar',
    type: 'UPA 24h',
    badgeTone: 'secondary',
    city: 'Porto Alegre',
    state: 'RS',
    address: 'Rua Jerônymo Zelmanovitz, 01 – São Sebastião, Porto Alegre/RS',
    phoneDisplay: '(51) 3368-1629',
    phoneHref: 'tel:5133681629',
    hours: '24 horas',
    lat: -30.0076,
    lng: -51.1442,
    review: pendingReview,
  },
  {
    id: 'poa-pa-bom-jesus',
    name: 'Pronto Atendimento Bom Jesus',
    type: 'Pronto Atendimento',
    badgeTone: 'secondary',
    city: 'Porto Alegre',
    state: 'RS',
    address: 'Rua Bom Jesus, 410 – Bom Jesus, Porto Alegre/RS',
    phoneDisplay: '(51) 3289-5424',
    phoneHref: 'tel:5132895424',
    hours: '24 horas',
    lat: -30.0465,
    lng: -51.1648,
    review: pendingReview,
  },
  {
    id: 'poa-pa-lomba-pinheiro',
    name: 'Pronto Atendimento Lomba do Pinheiro',
    type: 'Pronto Atendimento',
    badgeTone: 'secondary',
    city: 'Porto Alegre',
    state: 'RS',
    address: 'Estrada João de Oliveira Remião, 5110 – Lomba do Pinheiro, Porto Alegre/RS',
    phoneDisplay: '(51) 3289-8245',
    phoneHref: 'tel:5132898245',
    hours: '24 horas',
    lat: -30.1068,
    lng: -51.1245,
    review: pendingReview,
  },
  {
    id: 'poa-pa-cruzeiro-sul',
    name: 'Pronto Atendimento Cruzeiro do Sul',
    type: 'Pronto Atendimento',
    badgeTone: 'secondary',
    city: 'Porto Alegre',
    state: 'RS',
    address: 'Rua Professor Manoel Lobato, 151 – Santa Tereza, Porto Alegre/RS',
    phoneDisplay: '(51) 3289-4016',
    phoneHref: 'tel:5132894016',
    hours: '24 horas',
    lat: -30.0768,
    lng: -51.2224,
    review: pendingReview,
  },
  {
    id: 'poa-hps',
    name: 'Hospital de Pronto Socorro de Porto Alegre (HPS)',
    type: 'Hospital / Pronto-socorro 24h',
    badgeTone: 'secondary',
    city: 'Porto Alegre',
    state: 'RS',
    address: 'Largo Teodoro Herzl, s/nº – Bom Fim, Porto Alegre/RS',
    phoneDisplay: '(51) 3289-7999',
    phoneHref: 'tel:5132897999',
    hours: '24 horas',
    lat: -30.0384,
    lng: -51.2148,
    review: pendingReview,
  },
  {
    id: 'poa-hospital-conceicao',
    name: 'Hospital Nossa Senhora da Conceição',
    type: 'Hospital / Pronto-socorro 24h',
    badgeTone: 'secondary',
    city: 'Porto Alegre',
    state: 'RS',
    address: 'Av. Francisco Trein, 596 – Cristo Redentor, Porto Alegre/RS',
    phoneDisplay: '(51) 3357-2000',
    phoneHref: 'tel:5133572000',
    hours: '24 horas – SUS',
    lat: -30.0152,
    lng: -51.1612,
    review: pendingReview,
  },
  {
    id: 'poa-caps-altos-gloria',
    name: 'CAPS Altos da Glória',
    type: 'CAPS',
    badgeTone: 'primary',
    city: 'Porto Alegre',
    state: 'RS',
    address: 'Av. Oscar Pereira, 3391 – Cascata, Porto Alegre/RS',
    phoneDisplay: '(51) 3289-8258',
    phoneHref: 'tel:5132898258',
    hours: 'Segunda a Sexta, 08:00 - 18:00',
    lat: -30.0782,
    lng: -51.1983,
    review: pendingReview,
  },
  {
    id: 'poa-caps-bem-viver',
    name: 'CAPS II Bem Viver',
    type: 'CAPS',
    badgeTone: 'primary',
    city: 'Porto Alegre',
    state: 'RS',
    address: 'Rua Marco Polo, 278 – Cristo Redentor, Porto Alegre/RS',
    phoneDisplay: '(51) 3337-0726',
    phoneHref: 'tel:5133370726',
    hours: 'Segunda a Sexta, 08:00 - 18:00',
    lat: -30.0142,
    lng: -51.1578,
    review: pendingReview,
  },
  {
    id: 'poa-caps-cais-mental',
    name: 'CAPS II Cais Mental',
    type: 'CAPS',
    badgeTone: 'primary',
    city: 'Porto Alegre',
    state: 'RS',
    address: 'Av. José Bonifácio, 71 – Bom Fim, Porto Alegre/RS',
    phoneDisplay: '(51) 3289-5519',
    phoneHref: 'tel:5132895519',
    hours: 'Segunda a Sexta, 08:00 - 18:00',
    lat: -30.0368,
    lng: -51.2132,
    review: pendingReview,
  },
  {
    id: 'poa-caps-flor-de-maio',
    name: 'CAPS II Flor de Maio',
    type: 'CAPS',
    badgeTone: 'primary',
    city: 'Porto Alegre',
    state: 'RS',
    address: 'Rua Dr. Campos Velho, 1718 – Cristal, Porto Alegre/RS',
    phoneDisplay: '(51) 3289-5728',
    phoneHref: 'tel:5132895728',
    hours: 'Segunda a Sexta, 08:00 - 18:00',
    lat: -30.0795,
    lng: -51.2384,
    review: pendingReview,
  },
  {
    id: 'poa-caps-hcpa',
    name: 'CAPS II Hospital de Clínicas',
    type: 'CAPS',
    badgeTone: 'primary',
    city: 'Porto Alegre',
    state: 'RS',
    address: 'Rua São Manoel, 285 – Rio Branco, Porto Alegre/RS',
    phoneDisplay: '(51) 3359-8710',
    phoneHref: 'tel:5133598710',
    hours: 'Segunda a Sexta, 08:00 - 18:00',
    lat: -30.0378,
    lng: -51.2064,
    review: pendingReview,
  },
  {
    id: 'poa-caps-norte',
    name: 'CAPS III Norte',
    type: 'CAPS',
    badgeTone: 'primary',
    city: 'Porto Alegre',
    state: 'RS',
    address: 'Rua Conde de Porto Alegre, 71 – Floresta, Porto Alegre/RS',
    phoneDisplay: '(51) 3276-7013',
    phoneHref: 'tel:5132767013',
    hours: '24 horas',
    lat: -30.0212,
    lng: -51.2084,
    review: pendingReview,
  },
] satisfies ServiceDirectoryEntry[];
