import type { ServiceDirectoryEntry } from '../../../domain/services/types';
import { pendingReview } from './pendingReview';

export const saoLeopoldoServices = [
  // --- SÃO LEOPOLDO: UPAs, Hospitais e CAPS ---
  {
    id: 'sl-upa-scharlau',
    name: 'UPA Zona Norte / Scharlau – São Leopoldo',
    type: 'UPA 24h',
    badgeTone: 'secondary',
    city: 'São Leopoldo',
    state: 'RS',
    address: 'Rua Leopoldo Albino Scherer, 374 – Scharlau, São Leopoldo/RS',
    phoneDisplay: '(51) 3590-6646',
    phoneHref: 'tel:5135906646',
    hours: '24 horas',
    lat: -29.7346,
    lng: -51.1481,
    review: pendingReview,
  },
  {
    id: 'sl-ps-hospital-centenario',
    name: 'Pronto-Socorro do Hospital Centenário – São Leopoldo',
    type: 'Hospital / Pronto-socorro 24h',
    badgeTone: 'secondary',
    city: 'São Leopoldo',
    state: 'RS',
    address: 'Av. Theodomiro Porto da Fonseca, 799 – Fião, São Leopoldo/RS',
    phoneDisplay: '(51) 3591-1400',
    phoneHref: 'tel:5135911400',
    hours: '24 horas',
    lat: -29.7712,
    lng: -51.1465,
    review: pendingReview,
  },
  {
    id: 'sl-caps-capile',
    name: 'CAPS Capilé',
    type: 'CAPS',
    badgeTone: 'primary',
    city: 'São Leopoldo',
    state: 'RS',
    address: 'Rua Bento Gonçalves, 891 – Centro, São Leopoldo/RS',
    phoneDisplay: '(51) 2200-0761',
    phoneHref: 'tel:5122000761',
    hours: 'Segunda a Sexta, 08:00 - 18:00',
    lat: -29.7618,
    lng: -51.1472,
    review: pendingReview,
  },
  {
    id: 'sl-caps-ad',
    name: 'CAPS AD São Leopoldo',
    type: 'CAPS',
    badgeTone: 'primary',
    city: 'São Leopoldo',
    state: 'RS',
    address: 'Rua Ernesto Mutzel, 134 – Centro, São Leopoldo/RS',
    phoneDisplay: '(51) 2200-0760',
    phoneHref: 'tel:5122000760',
    hours: 'Álcool e outras drogas',
    lat: -29.7582,
    lng: -51.1449,
    review: pendingReview,
  },
] satisfies ServiceDirectoryEntry[];
