import type { ServicesContent } from '../../domain/services/types';

const pendingReview = {
  status: 'pending_review',
  reviewedBy: null,
  reviewedAt: null,
  notes: '',
} as const;

export const canoasServices = {
  id: 'canoas-services',
  version: '1.0.0',
  status: 'draft',
  locale: 'pt-BR',
  title: 'Rede de apoio à saúde',
  description: 'Encontre serviços de saúde e apoio próximos a você.',
  services: [
    // --- CANOAS: UPAs e Pronto Atendimento ---
    {
      id: 'canoas-upa-rio-branco',
      name: 'UPA Rio Branco',
      type: 'UPA 24h',
      badgeTone: 'secondary',
      city: 'Canoas',
      state: 'RS',
      address: 'Rua Cairu, 600 – Rio Branco, Canoas/RS',
      phoneDisplay: '(51) 3415-4500',
      phoneHref: 'tel:5134154500',
      hours: '24 horas',
      lat: -29.9388,
      lng: -51.1897,
      review: pendingReview,
    },
    {
      id: 'canoas-upa-liberty-dick-conter',
      name: 'UPA Liberty Dick Conter',
      type: 'UPA 24h',
      badgeTone: 'secondary',
      city: 'Canoas',
      state: 'RS',
      address: 'Rua Caçapava, 201 – Mathias Velho, Canoas/RS',
      phoneDisplay: '(51) 3415-4566',
      phoneHref: 'tel:5134154566',
      hours: '24 horas',
      lat: -29.9079,
      lng: -51.1963,
      review: pendingReview,
    },
    {
      id: 'canoas-upa-guajuviras',
      name: 'UPA Guajuviras',
      type: 'UPA 24h',
      badgeTone: 'secondary',
      city: 'Canoas',
      state: 'RS',
      address: 'Av. Boqueirão, 2.901 – Estância Velha, Canoas/RS',
      phoneDisplay: '(51) 3476-3698',
      phoneHref: 'tel:5134763698',
      hours: '24 horas',
      lat: -29.9035,
      lng: -51.1448,
      review: pendingReview,
    },
    {
      id: 'canoas-upa-sudeste-niteroi',
      name: 'UPA Sudeste / Niterói',
      type: 'UPA 24h',
      badgeTone: 'secondary',
      city: 'Canoas',
      state: 'RS',
      address: 'Rua Primeiro de Maio, 534 – Niterói, Canoas/RS',
      phoneDisplay: '(51) 3476-3448',
      phoneHref: 'tel:5134763448',
      hours: '24 horas',
      lat: -29.9351,
      lng: -51.1738,
      review: pendingReview,
    },
    {
      id: 'canoas-upa-do-idoso',
      name: 'UPA do Idoso',
      type: 'Pronto Atendimento',
      badgeTone: 'secondary',
      city: 'Canoas',
      state: 'RS',
      address: 'Rua Brasil, 438 – Centro, Canoas/RS',
      phoneDisplay: '(51) 3236-1632',
      phoneHref: 'tel:5132361632',
      hours: 'Pronto atendimento',
      lat: -29.9198,
      lng: -51.1791,
      review: pendingReview,
    },

    // --- CANOAS: CAPS ---
    {
      id: 'canoas-caps-praca-brasil',
      name: 'CAPS II Praça Brasil',
      type: 'CAPS',
      badgeTone: 'primary',
      city: 'Canoas',
      state: 'RS',
      address: 'Av. Getúlio Vargas, 7071 - Centro, Canoas - RS',
      phoneDisplay: '(51) 3236-1500',
      phoneHref: 'tel:5132361500',
      hours: 'Segunda a Sexta, 08:00 - 18:00',
      lat: -29.9145,
      lng: -51.1812,
      review: pendingReview,
    },
    {
      id: 'canoas-caps-novos-tempos',
      name: 'CAPS II Novos Tempos',
      type: 'CAPS',
      badgeTone: 'primary',
      city: 'Canoas',
      state: 'RS',
      address: 'Rua São Caetano, 102 – Marechal Rondon, Canoas/RS',
      phoneDisplay: '(51) 3076-9741',
      phoneHref: 'tel:5130769741',
      hours: 'Segunda a Sexta, 08:00 - 18:00',
      lat: -29.9073,
      lng: -51.1712,
      review: pendingReview,
    },
    {
      id: 'canoas-caps-recanto-girassois',
      name: 'CAPS III Recanto dos Girassóis',
      type: 'CAPS',
      badgeTone: 'primary',
      city: 'Canoas',
      state: 'RS',
      address: 'Rua Domingos Martins, 310 – Centro, Canoas/RS',
      phoneDisplay: '(51) 3076-9744',
      phoneHref: 'tel:5130769744',
      hours: '24 horas',
      lat: -29.9176,
      lng: -51.1865,
      review: pendingReview,
    },
    {
      id: 'canoas-caps-ad-travessia',
      name: 'CAPS AD III Travessia',
      type: 'CAPS',
      badgeTone: 'primary',
      city: 'Canoas',
      state: 'RS',
      address: 'Av. Guilherme Schell, 6250 - Centro, Canoas - RS',
      phoneDisplay: '(51) 3476-8800',
      phoneHref: 'tel:5134768800',
      hours: '24 horas',
      lat: -29.9161,
      lng: -51.1824,
      review: pendingReview,
    },

    // --- SÃO LEOPOLDO: UPAs, Hospitais e CAPS ---
    {
      id: 'sl-upa-scharlau',
      name: 'UPA Zona Norte / Scharlau – São Leopoldo',
      type: 'UPA 24h',
      badgeTone: 'secondary',
      city: 'São Leopoldo',
      state: 'RS',
      address: 'Rua Leopoldo Albino Scherer, 374 – Scharlau, São Leopoldo/RS',
      phoneDisplay: '(51) 3590-6646',
      phoneHref: 'tel:5135906646',
      hours: '24 horas',
      lat: -29.7346,
      lng: -51.1481,
      review: pendingReview,
    },
    {
      id: 'sl-ps-hospital-centenario',
      name: 'Pronto-Socorro do Hospital Centenário – São Leopoldo',
      type: 'Hospital / Pronto-socorro 24h',
      badgeTone: 'secondary',
      city: 'São Leopoldo',
      state: 'RS',
      address: 'Av. Theodomiro Porto da Fonseca, 799 – Fião, São Leopoldo/RS',
      phoneDisplay: '(51) 3591-1400',
      phoneHref: 'tel:5135911400',
      hours: '24 horas',
      lat: -29.7712,
      lng: -51.1465,
      review: pendingReview,
    },
    {
      id: 'sl-caps-capile',
      name: 'CAPS Capilé',
      type: 'CAPS',
      badgeTone: 'primary',
      city: 'São Leopoldo',
      state: 'RS',
      address: 'Rua Bento Gonçalves, 891 – Centro, São Leopoldo/RS',
      phoneDisplay: '(51) 2200-0761',
      phoneHref: 'tel:5122000761',
      hours: 'Segunda a Sexta, 08:00 - 18:00',
      lat: -29.7618,
      lng: -51.1472,
      review: pendingReview,
    },
    {
      id: 'sl-caps-ad',
      name: 'CAPS AD São Leopoldo',
      type: 'CAPS',
      badgeTone: 'primary',
      city: 'São Leopoldo',
      state: 'RS',
      address: 'Rua Ernesto Mutzel, 134 – Centro, São Leopoldo/RS',
      phoneDisplay: '(51) 2200-0760',
      phoneHref: 'tel:5122000760',
      hours: 'Álcool e outras drogas',
      lat: -29.7582,
      lng: -51.1449,
      review: pendingReview,
    },

    // --- NOVO HAMBURGO: UPAs, Hospitais e CAPS ---
    {
      id: 'nh-upa-centro',
      name: 'UPA Centro – Novo Hamburgo',
      type: 'UPA 24h',
      badgeTone: 'secondary',
      city: 'Novo Hamburgo',
      state: 'RS',
      address: 'Rua Visconde de Taunay, 134 – Rio Branco, Novo Hamburgo/RS',
      phoneDisplay: '(51) 3600-3123',
      phoneHref: 'tel:5136003123',
      hours: '24 horas',
      lat: -29.6914,
      lng: -51.1347,
      review: pendingReview,
    },
    {
      id: 'nh-upa-canudos',
      name: 'UPA Canudos – Novo Hamburgo',
      type: 'UPA 24h',
      badgeTone: 'secondary',
      city: 'Novo Hamburgo',
      state: 'RS',
      address: 'Rua Bartolomeu de Gusmão, 12 – Canudos, Novo Hamburgo/RS',
      phoneDisplay: '(51) 3097-1417',
      phoneHref: 'tel:5130971417',
      hours: '24 horas',
      lat: -29.6789,
      lng: -51.1098,
      review: pendingReview,
    },
    {
      id: 'nh-hospital-municipal',
      name: 'Hospital Municipal de Novo Hamburgo',
      type: 'Hospital / Pronto-socorro 24h',
      badgeTone: 'secondary',
      city: 'Novo Hamburgo',
      state: 'RS',
      address: 'Av. Pedro Adams Filho, 6520 – Operário, Novo Hamburgo/RS',
      phoneDisplay: '(51) 3272-3272',
      phoneHref: 'tel:5132723272',
      hours: '24 horas',
      lat: -29.6978,
      lng: -51.1275,
      review: pendingReview,
    },
    {
      id: 'nh-caps-canudos',
      name: 'CAPS Canudos',
      type: 'CAPS',
      badgeTone: 'primary',
      city: 'Novo Hamburgo',
      state: 'RS',
      address: 'Av. General Daltro Filho, 1660 – Canudos, Novo Hamburgo/RS',
      phoneDisplay: '(51) 3582-4206',
      phoneHref: 'tel:5135824206',
      hours: 'Segunda a Sexta, 08:00 - 18:00',
      lat: -29.6791,
      lng: -51.1112,
      review: pendingReview,
    },
    {
      id: 'nh-caps-santo-afonso',
      name: 'CAPS Santo Afonso',
      type: 'CAPS',
      badgeTone: 'primary',
      city: 'Novo Hamburgo',
      state: 'RS',
      address: 'Rua Babaçu, 58 – Santo Afonso, Novo Hamburgo/RS',
      phoneDisplay: '(51) 3580-1297',
      phoneHref: 'tel:5135801297',
      hours: 'Segunda a Sexta, 08:00 - 18:00',
      lat: -29.7182,
      lng: -51.1294,
      review: pendingReview,
    },
    {
      id: 'nh-caps-centro',
      name: 'CAPS Centro Novo Hamburgo',
      type: 'CAPS',
      badgeTone: 'primary',
      city: 'Novo Hamburgo',
      state: 'RS',
      address: 'Rua Joaquim Pedro Soares, 198 – Centro, Novo Hamburgo/RS',
      phoneDisplay: '(51) 3593-9573',
      phoneHref: 'tel:5135939573',
      hours: 'Segunda a Sexta, 08:00 - 18:00',
      lat: -29.6874,
      lng: -51.1291,
      review: pendingReview,
    },
    {
      id: 'nh-caps-ad-3',
      name: 'CAPS AD III Novo Hamburgo',
      type: 'CAPS',
      badgeTone: 'primary',
      city: 'Novo Hamburgo',
      state: 'RS',
      address: 'Rua Visconde de Taunay, 164 – Rio Branco, Novo Hamburgo/RS',
      phoneDisplay: '(51) 3600-8362',
      phoneHref: 'tel:5136008362',
      hours: '24 horas (Álcool e outras drogas)',
      lat: -29.6918,
      lng: -51.1352,
      review: pendingReview,
    },

    // --- ESTEIO E SAPUCAIA DO SUL ---
    {
      id: 'esteio-hospital-sao-camilo',
      name: 'Hospital São Camilo – Esteio',
      type: 'Hospital / Pronto-socorro 24h',
      badgeTone: 'secondary',
      city: 'Esteio',
      state: 'RS',
      address: 'Rua Castro Alves, 948 – Tamandaré, Esteio/RS',
      phoneDisplay: '(51) 2126-8300',
      phoneHref: 'tel:5121268300',
      hours: '24 horas',
      lat: -29.8542,
      lng: -51.1819,
      review: pendingReview,
    },
    {
      id: 'esteio-caps-aquarela',
      name: 'CAPS II Aquarela',
      type: 'CAPS',
      badgeTone: 'primary',
      city: 'Esteio',
      state: 'RS',
      address: 'Rua dos Ferroviários, 335 – Centro, Esteio/RS',
      phoneDisplay: '(51) 3473-0376',
      phoneHref: 'tel:5134730376',
      hours: 'Segunda a Sexta, 08:00 - 18:00',
      lat: -29.8572,
      lng: -51.1823,
      review: pendingReview,
    },
    {
      id: 'esteio-caps-ad-maos-dadas',
      name: 'CAPS AD Mãos Dadas',
      type: 'CAPS',
      badgeTone: 'primary',
      city: 'Esteio',
      state: 'RS',
      address: 'Rua 24 de Agosto, 500 – Centro, Esteio/RS',
      phoneDisplay: '(51) 2700-4370',
      phoneHref: 'tel:5127004370',
      hours: 'Álcool e outras drogas',
      lat: -29.8519,
      lng: -51.1802,
      review: pendingReview,
    },
    {
      id: 'sapucaia-upa-24h',
      name: 'UPA 24h Sapucaia do Sul',
      type: 'UPA 24h',
      badgeTone: 'secondary',
      city: 'Sapucaia do Sul',
      state: 'RS',
      address: 'ERS-118, esquina com Rua Ursa Maior – Nova Sapucaia, Sapucaia do Sul/RS',
      phoneDisplay: '(51) 3450-3082',
      phoneHref: 'tel:5134503082',
      hours: '24 horas',
      lat: -29.8247,
      lng: -51.1264,
      review: pendingReview,
    },
    {
      id: 'sapucaia-hospital-getulio-vargas',
      name: 'Hospital Municipal Getúlio Vargas – Sapucaia do Sul',
      type: 'Hospital / Pronto-socorro 24h',
      badgeTone: 'secondary',
      city: 'Sapucaia do Sul',
      state: 'RS',
      address: 'Rua Pinheiro Machado, 331 – Dihel, Sapucaia do Sul/RS',
      phoneDisplay: '(51) 3451-8200',
      phoneHref: 'tel:5134518200',
      hours: '24 horas',
      lat: -29.8329,
      lng: -51.1458,
      review: pendingReview,
    },
    {
      id: 'sapucaia-caps-bem-estar',
      name: 'CAPS II Bem Estar',
      type: 'CAPS',
      badgeTone: 'primary',
      city: 'Sapucaia do Sul',
      state: 'RS',
      address: 'Rua General Osório, esq. Rua Guerreiro Lima, s/nº – Sapucaia do Sul/RS',
      phoneDisplay: '(51) 3474-1833',
      phoneHref: 'tel:5134741833',
      hours: 'Segunda a Sexta, 08:00 - 18:00',
      lat: -29.8291,
      lng: -51.1462,
      review: pendingReview,
    },
    {
      id: 'sapucaia-caps-ad',
      name: 'CAPS AD Sapucaia do Sul',
      type: 'CAPS',
      badgeTone: 'primary',
      city: 'Sapucaia do Sul',
      state: 'RS',
      address: 'Rua Alfredo Juliano, 560 – Primor, Sapucaia do Sul/RS',
      phoneDisplay: '(51) 3474-4470',
      phoneHref: 'tel:5134744470',
      hours: 'Álcool e outras drogas',
      lat: -29.8354,
      lng: -51.1387,
      review: pendingReview,
    },

    // --- PORTO ALEGRE: UPAs, Pronto Atendimentos, Hospitais e CAPS ---
    {
      id: 'poa-upa-moacyr-scliar',
      name: 'UPA Zona Norte Moacyr Scliar',
      type: 'UPA 24h',
      badgeTone: 'secondary',
      city: 'Porto Alegre',
      state: 'RS',
      address: 'Rua Jerônymo Zelmanovitz, 01 – São Sebastião, Porto Alegre/RS',
      phoneDisplay: '(51) 3368-1629',
      phoneHref: 'tel:5133681629',
      hours: '24 horas',
      lat: -30.0076,
      lng: -51.1442,
      review: pendingReview,
    },
    {
      id: 'poa-pa-bom-jesus',
      name: 'Pronto Atendimento Bom Jesus',
      type: 'Pronto Atendimento',
      badgeTone: 'secondary',
      city: 'Porto Alegre',
      state: 'RS',
      address: 'Rua Bom Jesus, 410 – Bom Jesus, Porto Alegre/RS',
      phoneDisplay: '(51) 3289-5424',
      phoneHref: 'tel:5132895424',
      hours: '24 horas',
      lat: -30.0465,
      lng: -51.1648,
      review: pendingReview,
    },
    {
      id: 'poa-pa-lomba-pinheiro',
      name: 'Pronto Atendimento Lomba do Pinheiro',
      type: 'Pronto Atendimento',
      badgeTone: 'secondary',
      city: 'Porto Alegre',
      state: 'RS',
      address: 'Estrada João de Oliveira Remião, 5110 – Lomba do Pinheiro, Porto Alegre/RS',
      phoneDisplay: '(51) 3289-8245',
      phoneHref: 'tel:5132898245',
      hours: '24 horas',
      lat: -30.1068,
      lng: -51.1245,
      review: pendingReview,
    },
    {
      id: 'poa-pa-cruzeiro-sul',
      name: 'Pronto Atendimento Cruzeiro do Sul',
      type: 'Pronto Atendimento',
      badgeTone: 'secondary',
      city: 'Porto Alegre',
      state: 'RS',
      address: 'Rua Professor Manoel Lobato, 151 – Santa Tereza, Porto Alegre/RS',
      phoneDisplay: '(51) 3289-4016',
      phoneHref: 'tel:5132894016',
      hours: '24 horas',
      lat: -30.0768,
      lng: -51.2224,
      review: pendingReview,
    },
    {
      id: 'poa-hps',
      name: 'Hospital de Pronto Socorro de Porto Alegre (HPS)',
      type: 'Hospital / Pronto-socorro 24h',
      badgeTone: 'secondary',
      city: 'Porto Alegre',
      state: 'RS',
      address: 'Largo Teodoro Herzl, s/nº – Bom Fim, Porto Alegre/RS',
      phoneDisplay: '(51) 3289-7999',
      phoneHref: 'tel:5132897999',
      hours: '24 horas',
      lat: -30.0384,
      lng: -51.2148,
      review: pendingReview,
    },
    {
      id: 'poa-hospital-conceicao',
      name: 'Hospital Nossa Senhora da Conceição',
      type: 'Hospital / Pronto-socorro 24h',
      badgeTone: 'secondary',
      city: 'Porto Alegre',
      state: 'RS',
      address: 'Av. Francisco Trein, 596 – Cristo Redentor, Porto Alegre/RS',
      phoneDisplay: '(51) 3357-2000',
      phoneHref: 'tel:5133572000',
      hours: '24 horas – SUS',
      lat: -30.0152,
      lng: -51.1612,
      review: pendingReview,
    },
    {
      id: 'poa-caps-altos-gloria',
      name: 'CAPS Altos da Glória',
      type: 'CAPS',
      badgeTone: 'primary',
      city: 'Porto Alegre',
      state: 'RS',
      address: 'Av. Oscar Pereira, 3391 – Cascata, Porto Alegre/RS',
      phoneDisplay: '(51) 3289-8258',
      phoneHref: 'tel:5132898258',
      hours: 'Segunda a Sexta, 08:00 - 18:00',
      lat: -30.0782,
      lng: -51.1983,
      review: pendingReview,
    },
    {
      id: 'poa-caps-bem-viver',
      name: 'CAPS II Bem Viver',
      type: 'CAPS',
      badgeTone: 'primary',
      city: 'Porto Alegre',
      state: 'RS',
      address: 'Rua Marco Polo, 278 – Cristo Redentor, Porto Alegre/RS',
      phoneDisplay: '(51) 3337-0726',
      phoneHref: 'tel:5133370726',
      hours: 'Segunda a Sexta, 08:00 - 18:00',
      lat: -30.0142,
      lng: -51.1578,
      review: pendingReview,
    },
    {
      id: 'poa-caps-cais-mental',
      name: 'CAPS II Cais Mental',
      type: 'CAPS',
      badgeTone: 'primary',
      city: 'Porto Alegre',
      state: 'RS',
      address: 'Av. José Bonifácio, 71 – Bom Fim, Porto Alegre/RS',
      phoneDisplay: '(51) 3289-5519',
      phoneHref: 'tel:5132895519',
      hours: 'Segunda a Sexta, 08:00 - 18:00',
      lat: -30.0368,
      lng: -51.2132,
      review: pendingReview,
    },
    {
      id: 'poa-caps-flor-de-maio',
      name: 'CAPS II Flor de Maio',
      type: 'CAPS',
      badgeTone: 'primary',
      city: 'Porto Alegre',
      state: 'RS',
      address: 'Rua Dr. Campos Velho, 1718 – Cristal, Porto Alegre/RS',
      phoneDisplay: '(51) 3289-5728',
      phoneHref: 'tel:5132895728',
      hours: 'Segunda a Sexta, 08:00 - 18:00',
      lat: -30.0795,
      lng: -51.2384,
      review: pendingReview,
    },
    {
      id: 'poa-caps-hcpa',
      name: 'CAPS II Hospital de Clínicas',
      type: 'CAPS',
      badgeTone: 'primary',
      city: 'Porto Alegre',
      state: 'RS',
      address: 'Rua São Manoel, 285 – Rio Branco, Porto Alegre/RS',
      phoneDisplay: '(51) 3359-8710',
      phoneHref: 'tel:5133598710',
      hours: 'Segunda a Sexta, 08:00 - 18:00',
      lat: -30.0378,
      lng: -51.2064,
      review: pendingReview,
    },
    {
      id: 'poa-caps-norte',
      name: 'CAPS III Norte',
      type: 'CAPS',
      badgeTone: 'primary',
      city: 'Porto Alegre',
      state: 'RS',
      address: 'Rua Conde de Porto Alegre, 71 – Floresta, Porto Alegre/RS',
      phoneDisplay: '(51) 3276-7013',
      phoneHref: 'tel:5132767013',
      hours: '24 horas',
      lat: -30.0212,
      lng: -51.2084,
      review: pendingReview,
    },

    // --- Clínicas-escola e UBS ---
    {
      id: 'canoas-ubs-centro',
      name: 'UBS Centro de Saúde',
      type: 'UBS',
      badgeTone: 'secondary',
      city: 'Canoas',
      state: 'RS',
      address: 'Rua Quinze de Janeiro, 123 - Centro, Canoas - RS',
      phoneDisplay: '(51) 3462-1600',
      phoneHref: 'tel:5134621600',
      hours: 'Segunda a Sexta, 07:30 - 17:00',
      lat: -29.9192,
      lng: -51.1795,
      review: pendingReview,
    },
    {
      id: 'canoas-ulbra-clinica-psicologia',
      name: 'Clínica Escola de Psicologia - Ulbra',
      type: 'UNIVERSIDADE',
      badgeTone: 'neutral',
      city: 'Canoas',
      state: 'RS',
      address: 'Av. Farroupilha, 8001 - São José, Canoas - RS',
      phoneDisplay: '(51) 3477-9200',
      phoneHref: 'tel:5134779200',
      notes: 'Mediante agendamento prévio com valor social',
      lat: -29.9011,
      lng: -51.1578,
      review: pendingReview,
    },
  ],
} satisfies ServicesContent;
