import type { ServicesContent } from '../../domain/services/types';

const pendingReview = {
  status: 'pending_review',
  reviewedBy: null,
  reviewedAt: null,
  notes: '',
} as const;

export const canoasServices = {
  id: 'canoas-services',
  version: '0.1.0',
  status: 'draft',
  locale: 'pt-BR',
  title: 'Rede de apoio em Canoas',
  description: 'Encontre centros de atendimento e suporte próximos a você.',
  services: [
    {
      id: 'canoas-caps-praca-brasil',
      name: 'CAPS II Praça Brasil',
      type: 'CAPS',
      badgeTone: 'primary',
      city: 'Canoas',
      state: 'RS',
      address: 'Av. Getúlio Vargas, 7071 - Centro, Canoas - RS',
      phoneDisplay: '(51) 3236-1500',
      phoneHref: 'tel:5132361500',
      hours: 'Segunda a Sexta, 08:00 - 18:00',
      lat: -29.9145,
      lng: -51.1812,
      review: pendingReview,
    },
    {
      id: 'canoas-caps-novos-tempos',
      name: 'CAPS II Novos Tempos',
      type: 'CAPS',
      badgeTone: 'primary',
      city: 'Canoas',
      state: 'RS',
      address: 'Rua São Caetano, 102 - Marechal Rondon, Canoas - RS',
      phoneDisplay: '(51) 3076-9741',
      phoneHref: 'tel:5130769741',
      hours: 'Segunda a Sexta, 08:00 - 18:00',
      lat: -29.9073,
      lng: -51.1712,
      review: pendingReview,
    },
    {
      id: 'canoas-caps-recanto-girassois',
      name: 'CAPS III Recanto dos Girassóis',
      type: 'CAPS',
      badgeTone: 'primary',
      city: 'Canoas',
      state: 'RS',
      address: 'Rua Guilherme Morsch, 278 - Centro, Canoas - RS',
      phoneDisplay: '(51) 3425-7640',
      phoneHref: 'tel:5134257640',
      hours: '24 horas (acolhimento 08:00 - 18:00)',
      lat: -29.9176,
      lng: -51.1865,
      review: pendingReview,
    },
    {
      id: 'canoas-caps-ad-travessia',
      name: 'CAPS AD III Travessia',
      type: 'CAPS',
      badgeTone: 'primary',
      city: 'Canoas',
      state: 'RS',
      address: 'Av. Guilherme Schell, 6250 - Centro, Canoas - RS',
      phoneDisplay: '(51) 3476-8800',
      phoneHref: 'tel:5134768800',
      hours: '24 horas',
      lat: -29.9161,
      lng: -51.1824,
      review: pendingReview,
    },
    {
      id: 'canoas-caps-ad-amanhecer',
      name: 'CAPS AD III Amanhecer',
      type: 'CAPS',
      badgeTone: 'primary',
      city: 'Canoas',
      state: 'RS',
      address: 'Rua XV de Novembro, 82 - Nossa Senhora das Graças, Canoas - RS',
      phoneDisplay: '(51) 3476-8811',
      phoneHref: 'tel:5134768811',
      hours: '24 horas (acolhimento 08:00 - 18:00)',
      lat: -29.9234,
      lng: -51.1751,
      review: pendingReview,
    },
    {
      id: 'canoas-ubs-centro',
      name: 'UBS Centro de Saúde',
      type: 'UBS',
      badgeTone: 'secondary',
      city: 'Canoas',
      state: 'RS',
      address: 'Rua Quinze de Janeiro, 123 - Centro, Canoas - RS',
      phoneDisplay: '(51) 3462-1600',
      phoneHref: 'tel:5134621600',
      hours: 'Segunda a Sexta, 07:30 - 17:00',
      lat: -29.9192,
      lng: -51.1795,
      review: pendingReview,
    },
    {
      id: 'canoas-ulbra-clinica-psicologia',
      name: 'Clínica Escola de Psicologia - Ulbra',
      type: 'UNIVERSIDADE',
      badgeTone: 'neutral',
      city: 'Canoas',
      state: 'RS',
      address: 'Av. Farroupilha, 8001 - São José, Canoas - RS',
      phoneDisplay: '(51) 3477-9200',
      phoneHref: 'tel:5134779200',
      notes: 'Mediante agendamento prévio',
      lat: -29.9011,
      lng: -51.1578,
      review: pendingReview,
    },
  ],
} satisfies ServicesContent;
